[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://gxsncnggihsxxebceago.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_krq5gmJKpYgkOILvz6U3zg_eia9Lohi"

[[plugins]]
  package = "@netlify/plugin-nextjs"
